### ISSUE TITLE
Question about the structure of initialization

### ISSUE THREAD

**Issue by zetashift** [Vladar4/nimgame2#28]
I read through this: https://github.com/Vladar4/nimgame2/blob/master/STYLE.md#objects
and was wondering why not put all the initialization code in the `newSometype()` proc, is it just because it's cleaner?

My apologies if this is a silly question!

**Comment by Vladar4** [comment]
It's for the inheritance purposes. This way you can easily call parent's init procedure from its child's init (instead of initializing parent's fields manually):

```
proc initChild(child: Child) =
  child.initParent() # initializing parent's stuff
  # initializing child's stuff
```

Please, let me know if this answers your question.

P.S.: Right now there are plenty of `init()` procedures (instead of `initSomeType()`) in the code, written prior to the style guide. I plan to rename them for the next major release.

**Comment by zetashift** [comment]
Alright that indeed answers it perfectly :D!
