### ISSUE TITLE
[question] Possible project that might rely on nimgame2

### ISSUE THREAD

**Issue by JohnAD** [Vladar4/nimgame2#42]
In May, I'm considering writing a utility that would convert Scratch games to Nim. Essentially, I'd be writing a program that takes apart the .sb3 file and generates a directory that contains a complete nim project in a directory ready for cross-compilation.

As part of that, I'd need to choose a 2D game engine to target. This one seems fairly active and a reasonable target. But, before I choose it, a few key questions:

1. This engine uses the `sdl2_nim`  library that in theory can be used for generating code for Linux, Windows 10, MacOS, Android, and iOS. But in practice, does this fully work?

2. What is the ideal Nim compiler version to use. Specifically is 1.2 okay or is it better to specify an earlier version?

**Comment by Vladar4** [comment]
Greetings and thanks for the consideration!

1. I've tested `sdl2_nim` with Linux and Windows, because that's what I could run it on by myself. Everything else should be working *in theory*, but some platform-dependent components might very well require additional patches which I'll gladly accept be they provided.

2. Master branch of nimgame2 (v0.6.1) should work with Nim 1.2 (with some deprecation warnings for sure), but current `devel` (v0.7.0) is specifically optimized for it. I hope to get to releasing 0.7 soon enough, but it still needs some work and features to be added.
